### ISSUE TITLE
Doesn't work on twitter.com

### ISSUE THREAD

**Issue by yashi** [MaherSaleem/stay-focused-chrome-extension#3]
I have two version of Chrome on my Linux PC.
a) Version 85.0.4183.83 (Official Build) beta (64-bit)
b) Version 86.0.4240.8 (Official Build) dev (64-bit)

86 works just fine but 85 doesn't block twitter.com.  It _does_ block youtube and facebook, though.

Any idea?

BTW, a nice extension. I love it!

**Comment by MaherSaleem** [comment]
Hey @yashi,
could you please share an image with the list of website, so I may be able to figure out the issue.
Thanks :D

**Comment by yashi** [comment]
I'm really sorry about the noise...
I guess I accidentally clicked the toggle button on twitter.
Thanks for your time and sorry about it again.
Close.
